services:
  build-app:
    build: .
    volumes:
      - ./build_output:/app/build_output
    env_file:
      - .env
    working_dir: /app
    command: >
      sh -c '
      find . -type f -exec sed -i 's/fedorenko/$$PROJECT_NAME/g' {} + &&
      find . -type f -exec sed -i 's/Fedorenko/$$PROJECT_TITLE/g' {} + &&
      flutter pub get &&
      flutter build apk &&
      cp -r build/app/outputs /app/build_output/
      '